create table disasters(
	year int primary key,
	all_disaster_count int,
	drought_count int,
	earthquake_count int,
	extreme_temp_count int,
	extreme_weather_count int,
	flood_count int,
	impact_count int,
	landslide_count int,
	dry_mass_movement_count int,
	volcanic_count int,
	wildfire_count int,
	all_disaster_cost int,
	drought_cost int,
	earthquake_cost int,
	extreme_temp_cost int,
	extreme_weather_cost int,
	flood_cost int,
	impact_cost int,
	landslide_cost int,
	dry_mass_movement_cost int,
	volcanic_cost int,
	wildfire_cost int);
